#!/usr/bin/env bash

input=tests/circle
if (( $# >= 1 )) && [ -e tests/$1 ] ; then
    input=tests/$1
fi
echo "Comparing: $input"
make

bin/Euler < $input | awk '{if (count++%3==2) print $0;}' > Euler.txt
bin/DK    < $input | awk '{if (count++%3==2) print $0;}' > DK.txt
bin/KD    < $input | awk '{if (count++%3==2) print $0;}' > KD.txt
bin/KDK   < $input | awk '{if (count++%3==2) print $0;}' > KDK.txt
bin/DKD   < $input | awk '{if (count++%3==2) print $0;}' > DKD.txt
