#!/usr/bin/env bash

input=tests/circle
if (( $# >= 1 )) && [ -e tests/$1 ] ; then
    input=tests/$1
fi
echo "Comparing: $input"
make

tail -n1 $input > Euler.txt; bin/Euler < $input | awk '{if (count++%3==2) print $0;}' >> Euler.txt
tail -n1 $input > DK.txt;    bin/DK    < $input | awk '{if (count++%3==2) print $0;}' >> DK.txt
tail -n1 $input > KD.txt;    bin/KD    < $input | awk '{if (count++%3==2) print $0;}' >> KD.txt
tail -n1 $input > KDK.txt;   bin/KDK   < $input | awk '{if (count++%3==2) print $0;}' >> KDK.txt
tail -n1 $input > DKD.txt;   bin/DKD   < $input | awk '{if (count++%3==2) print $0;}' >> DKD.txt
